name: Feature Request
description: Suggest an idea or new feature for TASVideos
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand and evaluate your proposal.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: What other approaches could solve this problem?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the application does this feature relate to?
      options:
        - User Interface
        - Movie Submission
        - Publication System
        - User Management
        - Forum
        - API
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking work)
        - High (significantly improves workflow)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful.
      placeholder: |
        1. When a user wants to...
        2. When an admin needs to...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or examples from other sites.
      placeholder: Drag and drop images here or paste them...
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
          required: false
        - label: I can help with testing
          required: false
        - label: I can provide additional requirements/specifications
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request.
      placeholder: Any additional details that might be helpful...
    validations:
      required: false
