// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TASVideos.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("99999999999999_RemoveFourGameTables")]
partial class RemoveFourGameTables
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Migration designer file
    }
}
